//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Perfect11.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private  global::System.Resources.ResourceManager resourceMan;
        
        private  global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal  global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Perfect11.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal  global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Channel]
        ///OEM
        ///[VL]
        ///0.
        /// </summary>
        internal  string EI_CFG {
            get {
                return ResourceManager.GetString("EI_CFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;unattend xmlns=&quot;urn:schemas-microsoft-com:unattend&quot;&gt;
        ///    &lt;settings pass=&quot;oobeSystem&quot;&gt;
        ///        &lt;component name=&quot;Microsoft-Windows-Shell-Setup&quot; processorArchitecture=&quot;amd64&quot; publicKeyToken=&quot;31bf3856ad364e35&quot; language=&quot;neutral&quot; versionScope=&quot;nonSxS&quot; xmlns:wcm=&quot;http://schemas.microsoft.com/WMIConfig/2002/State&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///            &lt;OOBE&gt;
        ///                &lt;HideEULAPage&gt;true&lt;/HideEULAPage&gt;
        ///                &lt;HideOEMRegistrat [rest of string was truncated]&quot;;.
        /// </summary>
        internal  string unattend_OOBEAutomate {
            get {
                return ResourceManager.GetString("unattend_OOBEAutomate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1527c705-839a-4832-9118-54d4Bd6a0c89
        ///c5e2524a-ea46-4f67-841f-6a9465d9d515
        ///E2A4F912-2574-4A75-9BB0-0D023378592B
        ///F46D4000-FD22-4DB4-AC8E-4E1DDDE828FE
        ///InputApp
        ///Microsoft.AAD.BrokerPlugin
        ///Microsoft.AccountsControl
        ///Microsoft.Advertising.Xaml
        ///Microsoft.AsyncTextService
        ///Microsoft.BioEnrollment
        ///Microsoft.CredDialogHost
        ///Microsoft.ECApp
        ///Microsoft.LockApp
        ///Microsoft.MicrosoftEdge
        ///Microsoft.MicrosoftEdgeDevToolsClient
        ///Microsoft.NET
        ///Microsoft.PPIProjection
        ///Microsoft.Services.Store.Engagement
        ///Microsoft.V [rest of string was truncated]&quot;;.
        /// </summary>
        internal  string UWPSystemAppList {
            get {
                return ResourceManager.GetString("UWPSystemAppList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal  System.Drawing.Bitmap win11logo {
            get {
                object obj = ResourceManager.GetObject("win11logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal  System.Drawing.Bitmap win11wallpaperdark {
            get {
                object obj = ResourceManager.GetObject("win11wallpaperdark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal  System.Drawing.Bitmap win11wallpaperlight {
            get {
                object obj = ResourceManager.GetObject("win11wallpaperlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
